# Jafar Qutteineh 25-12-2016
# PRRT Config file
#
#######################################################################################
################################# Trajectories Configuration ###########################
name : 'FWD_CAPTG'                 # APTG name, used for debugging, and logs
ptg_module : 'prrt.ptg'            # name of the module where the PTG class is defined
ptg_class : 'CPTG'                 # name of the PTG class
alpha_max : 10.0                   # Maximum value for trajectory generation parameter (deg)
                                   # ,ideally 180 but it leads to invalid configurations
                                   # for the articulation angle
alpha_resolution : 1.0             # Resolution of alpha (deg)
phi_resolution : 3.0               # Resolution of articulation angle (deg)
K : 1                              # Set K = -1 to generate reverse trajectories, 1 for forward trajectories
dt : 0.001                         # Time step for simulating trajectories (s)
n_max : 10000                      # Maximum number of steps in trajectory
min_dist_between_cpoints : 0.02    # Minimum distance between two consecutive cpoints
k_theta : 1.0                      # Weight factor for angular distance


#################################### Grid Configuration ###############################
# This is a square grid where trajectories will be generated, and collisions tested.
# This grid is NOT the world grid.
grid_resolution : 0.1        # Resolution of the grid (m)
grid_size : 5.0              # Size of the grid (m)







    


