# Jafar Qutteineh 25-12-2016
# PRRT Config file
#
######################################################################################
################################### Planner ##########################################

#world_map_file : './maps/lot_caseStudy.png'        # Maximum absolute linear velocity (m/s)
#world_map_file : './maps/try.png'
world_map_file : './maps/antwayBIG.png'
#world_map_file : './maps/labyrinth_2.png'
#world_map_file : './maps/empty.png'
#world_map_file : './maps/lot.png'
#world_map_file : './maps/lot_A.png'
world_width : 200.0 #135.0 #117.6                            # Map width (m)
world_height : 200.0 # 75.0 #68.3                           # Map height (m)

aptg_files :                                 # List of APTGs pickle file
    #- './jar/fwd_captg.pkl'
    - './jar/bwd_captg.pkl'
    #- './jar/fwd_Alpha-a.pkl'


vehicle_config: './vehicle.yaml'        # Vehicle configuration file.


init_pose :                             # Vehicle initial pose
    x : 170.0                            # Vehicle initial x position (m)
    y : 150.0                            # Vehicle initial x position (m)
    theta : 0.0                         # Vehicle initial heading (Deg)
    phi : 0.0                           # Vehicle initial articulation angle (Deg)

goal_pose :                             # Vehicle goal pose
    x : 90.0                            # Vehicle goal x position (m)
    y : 95.0                            # Vehicle goal x position (m)
    theta : 60.0 #60.0                         # Vehicle goal heading (Deg)
    phi : 0.0                           # Vehicle goal articulation angle (Deg) - NOT USED!

D_max : 1.0                             # Maximum distance between two consecutive nodes
                                        # Note: Must be less than PTGs grid size
obs_R : 2.5                             # Multiple of grid_size, only obstacles within a circle
                                        # (with the robot at it's center and radius = obs_R* grid_size) will be checked. 
goal_dist_tolerance : 5.0               # Maximum distance (R2) to admit a candidate goal node (m)
goal_ang_tolerance : 180                # Maximum heading difference to admit a candidate goal node (deg)

rrt_bias : 0.1                          # bias for the random search of RRT [0 - 1]

max_count : 500                        # Planner will abort solving if iteration count exceeds this number
csv_out_file :  './out/solution.csv'    # A trace of the solution will as a csv list of poses and control command
                                        #  will be saved at this location
plot_tree_file : './out/tree.png'       # A plot of the final tree will be saved at this location,
                                        #  empty value means don't plot
plot_solution : './out/frame'           # Solution steps plot will be dumped at this location,
                                        #  empty value means don't plot
    
# Debugging
debug_tree_state  : 0                   # Plot the current state of the tree, values:
                                        #     1 : plot state on every iteration (Warning: will slow down solution)
                                        #     2 : plot state on every second iteration (Warning: will slow down solution)
                                        #     3 : plot state on every third  iteration (Warning: will slow down solution)
                                        #     n : plot state on every nth  iteration (Warning: will slow down solution)

debug_tree_state_file : './out/state'    #  tree_state will be plotted at this location. name will be post-fixed with
                                        #   iteration number


